on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [jazzy, kilted, lyrical]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
